== Development of new n-tier app


=== Overview

New app for teaching Advanced Ansible replacing earlier 
link:https://github.com/tonykay/bad-ansible[`bad-ansible`]. 

Overall architecture is:

          flask1
lb ->               postgres 
          flask2


*Concept change from `bad-ansible`*

n-tier app is designed to be well written *but* monolithic in its construction
to all useful exercises in refactoring, introducing modularity, and a backdrop
to create roles and or collections from sound a sound ansible code base.

=== Outline of main flow

* common
** setup yum repos (via satellite)
** setup firewalld
* setup postgres
** firewalld rule opening 5432
** install postgres 10
** no data load phase - come back to that?
* setup app tier
** firewalld rule opening 443

=== Development Environment

While intended to be deployed on a _real_ cloud or virtualization platform it
comes with a Vagrantfile and associated playbooks

==== Deploying the Database Tier


=== Notes:

Does firewalld need to be configured?

=== Resources

* Jeff Geerling's Ansible Galaxy Role
* Useful articles on Postgres
** Setting it up from scratch

https://opensource.com/article/17/6/ansible-postgresql-operations
  


== Credits

* Aditya Patawari and Vikas Aggarwal
** I used their phone app during debugging
** Shout out for their Ansible Automation Cookbook
* Jeff Geerlinguy for his Ansible Galaxy Postgres Role

